### ISSUE TITLE
How do you get this repo to save submissions locally?

### ISSUE THREAD

**Issue by rutkat** [norestlabs/mousekyc-be#41]
Looks like logins and submissions go to an API endpoint on a public norestlabs server. Why is this and how do you change it? @oleg-baturov

**Comment by oleg-baturov** [comment]
Which api do you mean?

**Comment by oleg-baturov** [comment]
@rutkat are you talking about admin apis?

**Comment by getcontrol** [comment]
Agreed, I want to host my user's sensitive ID docs on my own server not mousebelt.com

**Comment by gedanziger** [comment]
@rutkat @getcontrol ypdate the above lines.

**Comment by getcontrol** [comment]
Update 
_export const apiEndpoint = 'https://mousekyc-server.mousebelt.com';_
?

To localhost?

**Comment by getcontrol** [comment]
Local back-end server ?

**Comment by oleg-baturov** [comment]
yes
you need to update `apiEndpoint` to your backend server.

**Comment by rutkat** [comment]
@oleg-baturov @getcontrol It works by changing it to `export const apiEndpoint = 'http://localhost:3000';` You also need to get your own mailgun api key for `config/default.js` if you want to include email confirmation. However the mail send function has been commented out here to bypass another bug.  `https://github.com/norestlabs/mousekyc-be/blob/master/src/services/mail.service.js#L6` 
If you allow the mail to send with your unique api key, the new error is `data is not defined`.

**Comment by oleg-baturov** [comment]
@rutkat Updated mail send function.

**Comment by oleg-baturov** [comment]
it will work if mailgun key is correct.
I will close this issue.
