### ISSUE TITLE
Front end validation not displaying during sign up.

### ISSUE THREAD

**Issue by rutkat** [norestlabs/mousekyc-be#42]
While testing the sign up, the front end is not rendering the json return messages past line #28
https://github.com/norestlabs/mousekyc-be/blob/063185dc27f7dedf4b934fca3eda2ba9727795b9/src/controllers/admin.js#L28

**Comment by oleg-baturov** [comment]
@rutkat 
admin frontend shows `error message` correctly from server response.

![image](https://user-images.githubusercontent.com/32242962/50264175-2de98f00-0465-11e9-98e3-80848481977e.png)

**Comment by oleg-baturov** [comment]
I updated error message `Invalid email !` -> `email not found!`
@rutkat 
you will see it working on admin ui.

**Comment by rutkat** [comment]
Yes you are right @oleg-baturov The validation messages does show on the main screen. However it does not show on the "Sign up" screen after you click "Sign Up" 
<img width="463" alt="signup-validation" src="https://user-images.githubusercontent.com/4261178/50288791-e6352880-04a1-11e9-8607-2c3c0c41e0f1.png">

**Comment by oleg-baturov** [comment]
@rutkat 
Fixed by https://github.com/norestlabs/mousekyc-admin/commit/edc2d166097c91ca92fbceeda6d50cfbbb65319e
![image](https://user-images.githubusercontent.com/32242962/50293289-fa3b5300-04be-11e9-8774-568989e53a47.png)
