### ISSUE TITLE
web_1    | Error: Cannot find module './development.js'

### ISSUE THREAD

**Issue by nvdo49** [norestlabs/mousekyc-be#44]
I got an error when following the steps. Here are the steps I followed and there is the error. What did I miss? Thanks.
web_1    | Error: Cannot find module './development.js'
web_1    | [nodemon] app crashed - waiting for file changes before starting...

The steps:
git clone https://github.com/norestlabs/mousekyc-be.git
npm install

vi src/config/default.js
frontendBaseUrl: 'http://localhost:3006',
baseUrl: 'http://localhost:3000',

cp development.js.bak development.js

then run:
docker-compose up

The error: 

web_1    | [nodemon] starting `node src/app.js`
web_1    | internal/modules/cjs/loader.js:605
web_1    |     throw err;
web_1    |     ^
web_1    | 
web_1    | Error: Cannot find module './development.js'
web_1    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
web_1    |     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
web_1    |     at Module.require (internal/modules/cjs/loader.js:657:17)
web_1    |     at require (internal/modules/cjs/helpers.js:22:18)
web_1    |     at Object.<anonymous> (/app/src/config/index.js:3:16)
web_1    |     at Module._compile (internal/modules/cjs/loader.js:721:30)
web_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
web_1    |     at Module.load (internal/modules/cjs/loader.js:620:32)
web_1    |     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
web_1    |     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
web_1    |     at Module.require (internal/modules/cjs/loader.js:657:17)
web_1    |     at require (internal/modules/cjs/helpers.js:22:18)
web_1    |     at Object.<anonymous> (/app/src/app.js:15:16)
web_1    |     at Module._compile (internal/modules/cjs/loader.js:721:30)
web_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
web_1    |     at Module.load (internal/modules/cjs/loader.js:620:32)
web_1    | [nodemon] app crashed - waiting for file changes before starting...

**Comment by oleg-baturov** [comment]
Verified by 93d4a6f169a086da8a9bb55da13787b7018b17b8
